# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listinfo',
            options={'managed': False},
        ),
    ]
